version: '3'
services:
  redis-exporter:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: redis-exporter
    restart: always
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PROT=6379
      - REDIS_PASSWORD=123456
    ports:
      - 9121:9121